blog/urls.py
from blog.views import PostCreate, PostDetailView, PostUpdate, PostDelete, PostIndexView, PostDraftView, post_publish, \
    PostComment, comment_approve, comment_remove, contact, about, index, TagListView, TagCreateView, TagUpdateView, \
    TagDetailView, \
    TagDeleteView, CategoryListView, CategoryCreateView, CategoryDetailView, CategoryUpdateView, CategoryDeleteView
from django.urls import path
from .feeds import PostFeed

app_name = 'blog'
urlpatterns = [
    path('published/', PostIndexView.as_view(), name='post-list'),
    path('drafts/', PostDraftView.as_view(), name='post-draft-list'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('', index, name='home'),
    path('feeds/', PostFeed(), name='post-feed'),
    path('tags/', TagListView.as_view(), name='tag-list'),
    path('tag/create/', TagCreateView.as_view(), name='tag-create'),
    path('tag/<int:pk>/delete/', TagDeleteView.as_view(), name='tag-delete'),
    path('tag/<int:pk>/update/', TagUpdateView.as_view(), name='tag-update'),
    path('tag/<str:slug>/', TagDetailView.as_view(), name='tag-detail'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('category/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category-detail'),
    path('post/create/', PostCreate.as_view(), name='post-create'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment-remove'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment-approve'),
    path('post/<int:pk>/comment/', PostComment.as_view(), name='post-comment'),
    path('post/<int:pk>/publish/', post_publish, name='post-publish'),
    path('post/<int:pk>/delete/', PostDelete.as_view(), name='post-delete'),
    path('post/<int:pk>/update/', PostUpdate.as_view(), name='post-update'),
    path('post/<str:slug>/', PostDetailView.as_view(), name='post-detail'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import login, logout
from filebrowser.sites import site
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

admin.autodiscover()
sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [

    path('accounts/login/', login, name='login'),
    path('accounts/logout/', logout, {'next_page': '/'}, name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <- Here
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('blog.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from tinymce import HTMLField


# Create your models here.
# Custom Manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class DraftsManager(models.Manager):
    def get_queryset(self):
        return super(DraftsManager, self).get_queryset().filter(status='draft')


class Tag(models.Model):
    name = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, )
        super(Tag, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:tag-detail', kwargs={'slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, )
    slug = models.SlugField(max_length=150, unique=True, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:category-detail', kwargs={'slug': self.slug})


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    tags = models.ManyToManyField(Tag, blank=True)
    text = HTMLField('text')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    # The default Manager
    objects = models.Manager()

    # Custom Manager
    published = PublishedManager()
    drafts = DraftsManager()

    class Meta:
        ordering = ('-published_at',)
        index_together = (('id', 'slug'),)
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

    def publish(self):
        self.published_at = timezone.now()
        self.status = 'published'
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()

    created_at = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    class Meta:
        ordering = ('created_at',)
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.FileField(upload_to='uploads/user-images/')

blog/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post, Tag, Category


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    text = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': True, 'cols': 30, 'rows': 10}
        )
    )


class PostForm(forms.ModelForm):
    text = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': True, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ['title', 'tags', 'category', 'text']


class ContactForm(forms.Form):
    name = forms.CharField(required=False, max_length=100, help_text='100 characters max.')
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea)


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic
from django.contrib.messages.views import messages

from .models import Post, Comment, Tag, Category
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.mail import send_mail

from django.contrib.messages.views import SuccessMessageMixin
from .forms import CommentForm,ContactForm, TagForm, CategoryForm,PostForm



# CRUD OPERATIONS FOR CATEGORY MODEL
class CategoryListView(generic.ListView):
    model = Category
    context_object_name = 'categories'
    paginate_by = 5
    template_name = 'blog/category/category_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CategoryForm
        return context

    def post(self, *args, **kwargs):
        try:
            Category(name=self.request.POST['name']).save()
            messages.success(self.request, "Category added successfully")
            return redirect('blog:category-list')
        except:
            raise ValueError("Slug Field already exists")


class CategoryCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Category
    fields = ['name']
    success_message = "%(name)s was created successfully"
    template_name = 'blog/category/category_form.html'


class CategoryDetailView(generic.DetailView):
    model = Category
    query_pk_and_slug = True
    template_name = 'blog/category/category_detail.html'


class CategoryUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Category
    fields = ['name']
    success_message = "%(name)s was updated successfully"
    template_name = 'blog/category/category_form.html'


class CategoryDeleteView(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Category
    template_name = 'blog/category/category_confirm_delete.html'
    success_message = "%(title)s was deleted successfully"
    success_url = reverse_lazy('blog:category-list')


# CRUD OPERATIONS FOR TAG MODEL
class TagListView(generic.ListView):
    model = Tag
    context_object_name = 'tags'
    paginate_by = 5
    template_name = 'blog/tag/tag_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TagForm
        return context

    def post(self, request, *args, **kwargs):
        try:
            Tag(name=self.request.POST['name']).save()
            messages.success(self.request, "Tag added successfully")
            return redirect('blog:tag-list')
        except:
            raise ValueError("Slug Field already exists")


class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Tag
    fields = ['name']
    success_message = "%(name)s was created successfully"
    template_name = 'blog/tag/tag_form.html'


class TagDetailView(generic.DetailView):
    model = Tag
    query_pk_and_slug = True
    template_name = 'blog/tag/tag_detail.html'


class TagUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Tag
    fields = ['name']
    success_message = "%(name)s was updated successfully"
    template_name = 'blog/tag/tag_form.html'


class TagDeleteView(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Tag
    template_name = 'blog/tag/tag_confirm_delete.html'
    success_message = "%(title)s was deleted successfully"
    success_url = reverse_lazy('blog:tag-list')


# CRUD OPERATIONS VIEWS FOR POST MODEL
@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post-detail', slug=post.slug)


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post-detail', slug=comment.post.slug)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post-detail', slug=comment.post.slug)


class PostComment(SuccessMessageMixin, generic.CreateView):
    model = Comment
    fields = ['author', 'text', ]

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        form.instance.post = post
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post-detail', kwargs={'slug': self.object.post.slug})


# ----Class Based Views-------
class PostIndexView(generic.ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/post_list.html'

    def get_queryset(self):
        """Return the last five published questions."""
        # return Post.objects.filter(published_at__lte=timezone.now()).order_by('published_at')
        return Post.published.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()[:6]
        context['tags'] = Tag.objects.all()[:6]
        return context


class PostDraftView(LoginRequiredMixin, generic.ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/post/post_draft_list.html'
    paginate_by = 3

    def get_queryset(self):
        """Return the last five published questions."""

        return Post.drafts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()[:6]
        context['tags'] = Tag.objects.all()[:6]
        return context


class PostDetailView(generic.DetailView):
    model = Post
    query_pk_and_slug = True
    template_name = 'blog/post/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm
        return context


class PostCreate(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Post
    form_class = PostForm
    success_message = "%(title)s was created successfully"
    template_name = 'blog/post/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "New Blog Post"
        return context


class PostUpdate(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Post
    form_class = PostForm

    query_pk_and_slug = True
    success_message = "%(title)s was updated successfully"
    template_name = 'blog/post/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Update Blog Post"
        return context


class PostDelete(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Post
    success_message = "%(title)s was deleted successfully"
    success_url = reverse_lazy('blog:post-list')
    template_name = 'blog/post/post_confirm_delete.html'


# PROFILE VIEWS.
def about(request):
    return render(request, 'blog/pages/about.html')


def contact(request):
    title = 'Contact'
    form = ContactForm(request.POST or None)
    confirm_message = "Want to get in touch? Fill out the form below to send " \
                      "me a message and I will get back to you as soon as possible!"
    show_button = True
    if form.is_valid():
        print(request.POST)
        subject = 'Message from MyBlog'
        name = form.cleaned_data['name']
        message = form.cleaned_data['message']
        message = '{name} {message}'.format(name=name, message=message)
        emailFrom = form.cleaned_data['email']
        emailTo = [settings.EMAIL_HOST_USER]
        send_mail(subject, message, emailFrom, emailTo,fail_silently=False)
        title = 'Well {name}!.'.format(name=name)
        confirm_message = 'Thank You for the Message.We will get right back to you.'
        form = None
        show_button = False

    context = {'form': form, 'title': title, 'confirm_message': confirm_message, 'show_button': show_button}
    template = 'blog/pages/contact.html'
    return render(request, template, context)


def index(request):
    return render(request, 'blog/base.html')

blog/templates/blog/includes/backup-posts.html
<!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="my-4">Page Heading
                <small>Secondary Text</small>
            </h1>

            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">Post Title</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid
                        atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero
                        voluptate voluptatibus possimus, veniam magni quis!</p>
                    <a href="#" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on January 1, 2017 by
                    <a href="#">Start Bootstrap</a>
                </div>
            </div>

            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">Post Title</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid
                        atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero
                        voluptate voluptatibus possimus, veniam magni quis!</p>
                    <a href="#" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on January 1, 2017 by
                    <a href="#">Start Bootstrap</a>
                </div>
            </div>

            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">Post Title</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid
                        atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero
                        voluptate voluptatibus possimus, veniam magni quis!</p>
                    <a href="#" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on January 1, 2017 by
                    <a href="#">Start Bootstrap</a>
                </div>
            </div>

            <!-- Pagination -->
            <ul class="pagination justify-content-center mb-4">
                <li class="page-item">
                    <a class="page-link" href="#">&larr; Older</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#">Newer &rarr;</a>
                </li>
            </ul>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Search Widget -->
            <div class="card my-4">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
                    </div>
                </div>
            </div>

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">Web Design</a>
                                </li>
                                <li>
                                    <a href="#">HTML</a>
                                </li>
                                <li>
                                    <a href="#">Freebies</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">JavaScript</a>
                                </li>
                                <li>
                                    <a href="#">CSS</a>
                                </li>
                                <li>
                                    <a href="#">Tutorials</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Side Widget</h5>
                <div class="card-body">
                    You can put anything you want inside of these side widgets. They are easy to use, and feature the
                    new Bootstrap 4 card containers!
                </div>
            </div>

        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

{% if user.is_authenticated %}
<div class="row justify-content-center">
    <div class="col-lg-5 col-lg-offset-3 mx-auto">
        <a href="{% url 'blog:post-create' %}" class="top-menu">
             <span class="fa-stack fa-lg">
                 <i class="fas fa-circle fa-stack-2x "></i>
                 <i class="fa fa-plus fa-stack-1x fa-inverse " aria-hidden="true"></i>
             </span>Add new
        </a>
        <a href="{% url 'blog:post_draft_list' %}" class="top-menu">
            <span class="fa-stack fa-lg">
                 <i class="fas fa-circle fa-stack-2x"></i>
                 <i class="fa fa-clone fa-stack-1x fa-inverse " aria-hidden="true"></i>
             </span>
            Drafts
        </a>
    </div>
</div>
{% endif %}
{% for post in posts %}
<div class="post-preview">
    <a href="{{ post.get_absolute_url }}">
        <h2 class="post-title">
            {{ post.title }}
        </h2>
        <!--<h3 class="post-subtitle">-->
        <!--{{ post.text|safe }}-->
        <!--</h3>-->
    </a>
    <p class="post-meta">Posted by
        <a href="#">{{post.author.get_username}}</a>
        on {{post.published_at}}</p>
    <a href="{% url 'blog:post_detail' post.slug  %}">Comments: {{ post.approved_comments.count }}</a>
</div>
<hr>
{% empty %}
<p>No posts yet.</p>
{% endfor %}
{% if posts %}
<!-- Pager -->
<div class="clearfix">
    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
</div>
{% endif %}

blog/templates/blog/includes/list-sidebar.html
<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right">
    <!-- Action Widget -->
    {% if user.is_authenticated %}
    <div class="card my-4">
        <h5 class="card-header">Actions</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-unstyled mb-0">

                        <li style="margin-top:5px;margin-bottom:5px;">
                            <a class="btn btn-secondary" href="{% url 'blog:post-create' %}"><i
                                    class="fas fa-plus"></i> Add new Post</a>
                        </li>
                        {% ifequal request.path '/published/' %}
                        <li style="margin-top:5px;margin-bottom:5px;">
                            <a class="btn btn-default" href="{% url 'blog:post-draft-list' %}"><i
                                    class="fas  fa-list"></i> Draft Posts</a>

                        </li>
                        {% endifequal %}
                        {% ifequal request.path '/drafts/' %}
                        <li style="margin-top:5px;margin-bottom:5px;">
                            <a class="btn btn-default" href="{% url 'blog:post-list' %}"><i
                                    class="fas  fa-list"></i>Published Posts</a>

                        </li>
                        {% endifequal %}

                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <!-- Search Widget -->
    <!--<div class="card my-4">-->
    <!--<h5 class="card-header">Search</h5>-->
    <!--<div class="card-body">-->
    <!--<div class="input-group">-->
    <!--<input type="text" class="form-control" placeholder="Search for...">-->
    <!--<span class="input-group-btn">-->
    <!--<button class="btn btn-secondary" type="button">Go!</button>-->
    <!--</span>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    {% if categories %}
    <!-- Categories Widget -->
    <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% if categories %}
                        {% for category in categories %}
                        <li>
                            <a href="{{category.get_absolute_url}}">{{category}}</a>
                        </li>
                        {% empty %}
                        <p>No categories yet</p>
                        {% endfor %}
                        {% endif %}
                    </ul>
                </div>

            </div>
        </div>
    </div>
    {% endif %}
    {% if tags %}
    <div class="card my-4">
        <h5 class="card-header">Tags</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% if tags %}
                        {% for tag in tags %}
                        <li>
                            <a href="{{tag.get_absolute_url}}">{{tag}}</a>
                        </li>
                        {% empty %}
                        <p>No tags yet</p>
                        {% endfor %}
                        {% endif %}
                    </ul>
                </div>

            </div>
        </div>
    </div>
    {% endif %}

    <!-- Side Widget -->
    <!-- Sidebar Widgets Column -->

    <div class="card my-4">
        <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django',
                follow up the tutorial to learn how we made it..!</p>
            <a href="#"
               class="btn btn-danger">Know more!</a>
        </div>
    </div>


</div>

blog/templates/blog/includes/navigation-panel.html
<!-- Navigation -->
{% url 'blog:post-list' as post_list %}
{% url 'blog:about'  as about %}
{% url 'blog:contact'  as contact %}
{% url 'blog:home'  as home %}
{% url 'login'  as login %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">
    <div class="container">
        <a class="navbar-brand" href="#">Oenga John</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto  nav-fill w-100 ">
                <li class="nav-item {% if request.path == home %}active{% endif %}">
                    <a class="nav-link " href="{% url 'blog:home' %}">Home

                    </a>
                </li>
                <li class="nav-item {% if request.path == post_list %}active{% endif %}">
                    <a class="nav-link" href="{% url 'blog:post-list' %}">Blog</a>
                </li>
                <li class="nav-item {% if request.path == about %}active{% endif %}">
                    <a class="nav-link" href="{% url 'blog:about' %}">About</a>
                </li>

                <li class="nav-item {% if request.path == contact %}active{% endif %}">
                    <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Welcome {{ user.get_username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'blog:post-list' %}">Posts</a>
                        <a class="dropdown-item" href="{% url 'blog:category-list' %}">Categories</a>
                        <a class="dropdown-item" href="{% url 'blog:tag-list' %}">Tags</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}" onclick="event.preventDefault();
                         document.getElementById('frm-logout').submit();">Logout</a>
                        <form id="frm-logout" action="{% url 'logout' %}" method="POST" style="display: none;">
                            {% csrf_token %}
                        </form>
                    </div>
                </li>
                {% else %}
                <li class="nav-item {% if request.path == login %}active{% endif %}">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>