blog/urls.py
from blog.views import PostCreate, PostDetailView, PostUpdate, PostDelete, PostIndexView, PostDraftView, post_publish, \
    PostComment, comment_approve, comment_remove, contact, about, index, TagListView, TagCreateView, TagUpdateView, \
    TagDetailView, \
    TagDeleteView, CategoryListView, CategoryCreateView, CategoryDetailView, CategoryUpdateView, CategoryDeleteView
from django.urls import path
from .feeds import PostFeed

app_name = 'blog'
urlpatterns = [
    path('published/', PostIndexView.as_view(), name='post-list'),
    path('drafts/', PostDraftView.as_view(), name='post-draft-list'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('', index, name='home'),
    path('feeds/', PostFeed(), name='post-feed'),
    path('tags/', TagListView.as_view(), name='tag-list'),
    path('tag/create/', TagCreateView.as_view(), name='tag-create'),
    path('tag/<int:pk>/delete/', TagDeleteView.as_view(), name='tag-delete'),
    path('tag/<int:pk>/update/', TagUpdateView.as_view(), name='tag-update'),
    path('tag/<str:slug>/', TagDetailView.as_view(), name='tag-detail'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('category/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category-detail'),
    path('post/create/', PostCreate.as_view(), name='post-create'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment-remove'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment-approve'),
    path('post/<int:pk>/comment/', PostComment.as_view(), name='post-comment'),
    path('post/<int:pk>/publish/', post_publish, name='post-publish'),
    path('post/<int:pk>/delete/', PostDelete.as_view(), name='post-delete'),
    path('post/<int:pk>/update/', PostUpdate.as_view(), name='post-update'),
    path('post/<str:slug>/', PostDetailView.as_view(), name='post-detail'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import login, logout
from filebrowser.sites import site
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

admin.autodiscover()
sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [

    path('accounts/login/', login, name='login'),
    path('accounts/logout/', logout, {'next_page': '/'}, name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <- Here
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('blog.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from tinymce import HTMLField


# Create your models here.
# Custom Manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class DraftsManager(models.Manager):
    def get_queryset(self):
        return super(DraftsManager, self).get_queryset().filter(status='draft')


class Tag(models.Model):
    name = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, )
        super(Tag, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:tag-detail', kwargs={'slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, )
    slug = models.SlugField(max_length=150, unique=True, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:category-detail', kwargs={'slug': self.slug})


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    tags = models.ManyToManyField(Tag, blank=True)
    text = HTMLField('text')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    # The default Manager
    objects = models.Manager()

    # Custom Manager
    published = PublishedManager()
    drafts = DraftsManager()

    class Meta:
        ordering = ('-published_at',)
        index_together = (('id', 'slug'),)
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

    def publish(self):
        self.published_at = timezone.now()
        self.status = 'published'
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()

    created_at = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    class Meta:
        ordering = ('created_at',)
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.FileField(upload_to='uploads/user-images/')

blog/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post, Tag, Category


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    text = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': True, 'cols': 30, 'rows': 10}
        )
    )


class PostForm(forms.ModelForm):
    text = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': True, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ['title', 'tags', 'category', 'text']


class ContactForm(forms.Form):
    name = forms.CharField(required=False, max_length=100, help_text='100 characters max.')
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea)


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic
from django.contrib.messages.views import messages

from .models import Post, Comment, Tag, Category
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.mail import send_mail

from django.contrib.messages.views import SuccessMessageMixin
from .forms import CommentForm,ContactForm, TagForm, CategoryForm,PostForm



# CRUD OPERATIONS FOR CATEGORY MODEL
class CategoryListView(generic.ListView):
    model = Category
    context_object_name = 'categories'
    paginate_by = 5
    template_name = 'blog/category/category_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CategoryForm
        return context

    def post(self, *args, **kwargs):
        try:
            Category(name=self.request.POST['name']).save()
            messages.success(self.request, "Category added successfully")
            return redirect('blog:category-list')
        except:
            raise ValueError("Slug Field already exists")


class CategoryCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Category
    fields = ['name']
    success_message = "%(name)s was created successfully"
    template_name = 'blog/category/category_form.html'


class CategoryDetailView(generic.DetailView):
    model = Category
    query_pk_and_slug = True
    template_name = 'blog/category/category_detail.html'


class CategoryUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Category
    fields = ['name']
    success_message = "%(name)s was updated successfully"
    template_name = 'blog/category/category_form.html'


class CategoryDeleteView(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Category
    template_name = 'blog/category/category_confirm_delete.html'
    success_message = "%(title)s was deleted successfully"
    success_url = reverse_lazy('blog:category-list')


# CRUD OPERATIONS FOR TAG MODEL
class TagListView(generic.ListView):
    model = Tag
    context_object_name = 'tags'
    paginate_by = 5
    template_name = 'blog/tag/tag_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TagForm
        return context

    def post(self, request, *args, **kwargs):
        try:
            Tag(name=self.request.POST['name']).save()
            messages.success(self.request, "Tag added successfully")
            return redirect('blog:tag-list')
        except:
            raise ValueError("Slug Field already exists")


class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Tag
    fields = ['name']
    success_message = "%(name)s was created successfully"
    template_name = 'blog/tag/tag_form.html'


class TagDetailView(generic.DetailView):
    model = Tag
    query_pk_and_slug = True
    template_name = 'blog/tag/tag_detail.html'


class TagUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Tag
    fields = ['name']
    success_message = "%(name)s was updated successfully"
    template_name = 'blog/tag/tag_form.html'


class TagDeleteView(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Tag
    template_name = 'blog/tag/tag_confirm_delete.html'
    success_message = "%(title)s was deleted successfully"
    success_url = reverse_lazy('blog:tag-list')


# CRUD OPERATIONS VIEWS FOR POST MODEL
@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post-detail', slug=post.slug)


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post-detail', slug=comment.post.slug)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post-detail', slug=comment.post.slug)


class PostComment(SuccessMessageMixin, generic.CreateView):
    model = Comment
    fields = ['author', 'text', ]

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        form.instance.post = post
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post-detail', kwargs={'slug': self.object.post.slug})


# ----Class Based Views-------
class PostIndexView(generic.ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/post_list.html'

    def get_queryset(self):
        """Return the last five published questions."""
        # return Post.objects.filter(published_at__lte=timezone.now()).order_by('published_at')
        return Post.published.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()[:6]
        context['tags'] = Tag.objects.all()[:6]
        return context


class PostDraftView(LoginRequiredMixin, generic.ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/post/post_draft_list.html'
    paginate_by = 3

    def get_queryset(self):
        """Return the last five published questions."""

        return Post.drafts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()[:6]
        context['tags'] = Tag.objects.all()[:6]
        return context


class PostDetailView(generic.DetailView):
    model = Post
    query_pk_and_slug = True
    template_name = 'blog/post/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm
        return context


class PostCreate(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Post
    form_class = PostForm
    success_message = "%(title)s was created successfully"
    template_name = 'blog/post/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "New Blog Post"
        return context


class PostUpdate(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Post
    form_class = PostForm

    query_pk_and_slug = True
    success_message = "%(title)s was updated successfully"
    template_name = 'blog/post/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Update Blog Post"
        return context


class PostDelete(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Post
    success_message = "%(title)s was deleted successfully"
    success_url = reverse_lazy('blog:post-list')
    template_name = 'blog/post/post_confirm_delete.html'


# PROFILE VIEWS.
def about(request):
    return render(request, 'blog/pages/about.html')


def contact(request):
    title = 'Contact'
    form = ContactForm(request.POST or None)
    confirm_message = "Want to get in touch? Fill out the form below to send " \
                      "me a message and I will get back to you as soon as possible!"
    show_button = True
    if form.is_valid():
        print(request.POST)
        subject = 'Message from MyBlog'
        name = form.cleaned_data['name']
        message = form.cleaned_data['message']
        message = '{name} {message}'.format(name=name, message=message)
        emailFrom = form.cleaned_data['email']
        emailTo = [settings.EMAIL_HOST_USER]
        send_mail(subject, message, emailFrom, emailTo,fail_silently=False)
        title = 'Well {name}!.'.format(name=name)
        confirm_message = 'Thank You for the Message.We will get right back to you.'
        form = None
        show_button = False

    context = {'form': form, 'title': title, 'confirm_message': confirm_message, 'show_button': show_button}
    template = 'blog/pages/contact.html'
    return render(request, template, context)


def index(request):
    return render(request, 'blog/base.html')

blog/templates/blog/post/comment_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>New comment</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="save btn btn-default">Send</button>
        </form>
    </div>
</div>
{% endblock content %}
{% block js %}

<script type="text/javascript">
    tinymce.init({
        selector: 'textarea',
        setup: function (editor) {
            editor.on('change', function (e) {
                editor.save();
            });
        }
    });

</script>
{% endblock js %}

blog/templates/blog/post/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
<div class="row" style="margin-bottom:20px;">
    <div class="col-md-6 col-md-offset-3">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete <b>"{{ object }}"</b>?</p><br/>
            <input class="save btn btn-danger" type="submit" value="Confirm"/>
        </form>
    </div>
</div>
{% endblock content %}

blog/templates/blog/post/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row ">
    {% if not user.is_authenticated %}
    <div class="col-md-2"></div>
    {% endif %}
    <div class="col-md-9 card mb-4  mt-4 left  top">
        <div class="card-body">
            <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
            <p class=" text-muted">{{ post.author }} |
                {% if post.published_at %}
                Published On {{ post.published_at }}
                {% else %}
                {{ post.created_at }}
                {% endif %}
            </p>

            <div class="tags">
                {% for tag in post.tags.all %}
                <span class="label label-default" style="background:#6c757d;color:#fff;border-top-left-radius: 0.25rem;
    border-top-right-radius: 0.25rem;
    border-bottom-right-radius: 0.25rem;
    border-bottom-left-radius: 0.25rem;"> {{tag}}</span>
                {% empty %}
                No tags yet.
                {% endfor %}
            </div>
            <hr>


            <p class="card-text ">{{ post.text | safe }}</p>
        </div>
    </div>
    <div class="col-md-3">
        <!-- Search Widget -->
        {% if user.is_authenticated %}
        <div class="card my-4">
            <h5 class="card-header">Actions</h5>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <ul class="list-unstyled mb-0">

                            {% if post.published_at %}
                            {% else %}
                            <li>
                                <a class="btn btn-secondary" href="{% url 'blog:post-publish' post.pk %}"> <i
                                        class="fas fa-upload"></i> Publish</a>
                            </li>
                            {% endif %}
                            <li style="margin-top:5px;margin-bottom:5px;">
                                <a class="btn btn-primary" href="{% url 'blog:post-update' pk=post.pk   %}"> <i
                                        class="fas fa-edit"></i> Edit</a>
                            </li>
                            <li style="margin-top:5px;margin-bottom:5px;">
                                <a class="btn btn-danger" href="{% url 'blog:post-delete' pk=post.pk   %}"><i
                                        class="fas fa-times"></i> Delete</a>
                            </li>
                            <li style="margin-top:5px;margin-bottom:5px;">
                                <a class="btn btn-secondary" href="{% url 'blog:post-create' %}"><i
                                        class="fas fa-plus"></i> Add new Post</a>
                            </li>
                            <li style="margin-top:5px;margin-bottom:5px;">
                                <a class="btn btn-default" href="{% url 'blog:post-draft-list' %}"><i
                                        class="fas  fa-list"></i> Drafts</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

</div>
{% if post.published_at %}
<div class="row">
    {% if not user.is_authenticated %}
    <div class="col-md-2"></div>
    {% endif %}
    <div class="col-md-9">
        <h3>Comments:</h3>
        {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
        <div>
            <div>
                <strong>{{ comment.author }}</strong> {{ comment.created_at }}
                {% if not comment.approved_comment %}
                <a class="btn btn-danger" href="{% url 'blog:comment-remove' pk=comment.pk %}">remove</a>
                <a class="btn btn-warning" href="{% url 'blog:comment-approve' pk=comment.pk %}"> Approve</a>
                {% endif %}
            </div>

            <p>{{ comment.text|safe}}</p>
        </div>
        {% else %}
        <p>No comments approved yet or this post :(</p>
        {% endif %}
        {% empty %}
        <p>No comments here yet :(</p>
        {% endfor %}
        <hr>
        <h3 class="comment">Leave a comment:</h3>
        <div class="row">
            <div class="col-md-10 col-md-offset-1 mx-auto">
                <form action="{% url 'blog:post-comment' pk=post.pk %}" method="post">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input class="btn btn-primary" type="submit" value="Save Comment">
                </form>
            </div>
        </div>

    </div>
</div>
</div>
{% endif %}


{% endblock content%}
{% block js %}
<script src="{% static 'blog/js/tinymce.min.js' %}"></script>
<script>
        tinymce.init({
            selector:'textarea',
            height:200,
        	plugins:'link code codesample image imagetools wordcount lists  preview table autolink visualblocks visualchars textcolor save link image media',
        	toolbar1:' preview bold italic underline | fontselect,fontsizeselect  | forecolor backcolor | alignleft alignright |aligncenter alignjustify | indent outdent | bullist numlist table | link image media | codesample |',
            menubar:false,
            setup: function (editor) {
            editor.on('change', function (e) {
                editor.save();
            });
        }
         });

</script>
{% endblock js %}

blog/templates/blog/post/post_draft_list.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<!-- Blog Entries Column -->
<div class="row">
    <div class="col-md-8">


        <h1 class="my-4">Posts
            <small>Drafts</small>
        </h1>
        {% for post in posts %}
        <!-- Blog Post -->
        <div class="card mb-4">
            <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
            <div class="card-body">
                <h2 class="card-title"> {{ post.title }} </h2>
                <p class="card-text"></p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">View Details &rarr;</a>

            </div>
            <div class="card-footer text-muted">
                Created on {{post.created_at}} by
                <a href="#">{{post.author.get_username}}</a>

            </div>
        </div>
        {% empty %}
        <p>No posts yet.</p>
        {% endfor %}


        {% include 'blog/includes/pagination.html' %}

    </div>
    {% include 'blog/includes/list-sidebar.html' %}

</div>
</div>

{% endblock %}

blog/templates/blog/post/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
<link href="{% static 'blog/css/select2.min.css' %} " rel="stylesheet">
{% endblock css %}f
{% block content %}
<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-9">
        <h3>{{title}}</h3>
        {{ form.media }}
        <div class="row form-error">
            <div class="column" id="content">
                <form method="post" action='' enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Save">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block js %}
<script src="{% static 'blog/js/select2.min.js' %}"></script>
<script type="text/javascript">
    $('.selectmultiple').select2();



</script>
{% endblock js %}

blog/templates/blog/post/post_list.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
<!-- Page Content -->

{% if user.is_authenticated %}
<div class="row justify-content-center">
    <div class="col-lg-9 mx-auto"></div>
    <div class="col-lg-3 mx-auto">

    </div>
</div>
{% endif %}


<div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">


        <h1 class="my-4">Posts
            <small>Published</small>
        </h1>
        {% for post in posts %}
        <!-- Blog Post -->
        <div class="card mb-4">
            <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
            <div class="card-body">
                <h2 class="card-title"> {{ post.title }} </h2>
                <p class="card-text"></p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
                <a href="{% url 'blog:post-detail' post.slug  %}">Comments: {{ post.approved_comments.count }}</a>
            </div>
            <div class="card-footer text-muted">
                Posted on {{post.published_at}} by
                <a href="#">{{post.author.get_username}}</a>

            </div>
        </div>
        {% empty %}
        <p>No posts yet.</p>
        {% endfor %}
        {% include 'blog/includes/pagination.html' %}

    </div>

      {% include 'blog/includes/list-sidebar.html' %}
</div>
<!-- /.row -->


{% endblock content %}